---
title: LTC NatWiss Crew
author:
  - name: Dr. Bjoern Braunstein
    email: braunstein@dshs-koeln.de
    url: https://www.bjoernbraunstein.com
    affiliation: __German Sport University__ <br> Institute of Biomechanics and Orthopaedics <br> Institute of Movement- and Neuroscience
    affiliation-url: https://www.dshs-koeln.de
    orcid: 0000-0002-5173-8916
  - name: Dr. Robert Rein
    email: r.rein@dshs-koeln.de
    affiliation: __German Sport University__ <br> Institute of Training and Computer Science
    orcid: 0000-0001-7059-5319
  - name: Dr. Florian Seifriz
    email: seifriz@dshs-koeln.de
    affiliation: __German Sport University__ <br> Institute of Training and Computer Science
abstract: hier ein wenig text hier ein wenig text hier ein wenig text hier ein wenig text hier ein wenig text hier ein wenig text hier ein wenig text hier ein wenig text hier ein wenig texthier ein wenig text hier ein wenig text hier ein wenig text hier ein wenig text hier ein wenig text.
doi: 100.100.100.100
format: 
  html:
    toc: true
    code-fold: false
    code-line-numbers: true
    code-copy: true
    citations-hover: true
    citation-location: document #margin
bibliography: "lit.bib"
csl: "job.csl"
#csl: "gait-and-posture.csl"
link-citations: true
linkcolor: blue

license: CC BY
---

::: callout-important
Sollten wir nicht auf das Format 'Book' oder website wechseln? Dann einfach ein Quarto 'Publish' befehl als GithubPages publishen https://quarto.org/docs/publishing/github-pages.html
:::

# LTC

Dies ist ein Repository für den Studiengang LTC für die Kurse LTC4, LTCXY und LTC12. Sie finden hier vorbereitende Materialien die als Voraussetzung angesehen werden, sowie Zusatzmaterial zum nachlesen. Soweit rechtlich möglich sind die Materialien entweder direkt verfügbar oder per Links angezeigt.

$$
Motto_{LTC} \leftarrow Almost \, doesn't \, count
$$ {#eq-Motto}

# LTC4

## "Erwartungen" an die R/RStudio Vorkenntnisse zu Vorlesungsbeginn

##### 1. Installation von R und RStudio

Video: <https://www.youtube.com/watch?v=X_Mxya2Fis0>

##### 2. Erste Schritte Einführung in RStudio

Video: <https://www.youtube.com/watch?v=tyvEHQszZJs>

##### 3. Zusätzliche Packages installieren

Video: <https://www.youtube.com/watch?v=YD8OLpvkHD8>

::: {.callout-important appearance="simple"}
## Bitte folgende Packages installieren: "tidyverse" und "ggplot2"
:::

##### 4. Grundkenntnisse in R

Einführung in R: <https://methodenlehre.github.io/einfuehrung-in-R/index.html>

::: {.callout-important appearance="simple"}
## Grundlegendes Verständis der Kapitel 0 bis 2 wird erwartet.
:::

## Readings
Healy, K. (2018). Data visualization: a practical introduction. Princeton University Press. <https://socviz.co/>

Nordmann, E., McAleer, P., Toivo, W., Paterson, H., & DeBruine, L. M. (2022). Data Visualization Using R for Researchers Who Do Not Use R. Advances in Methods and Practices in Psychological Science. <https://doi.org/10.1177/25152459221074654>

Peng, R.D.: R programming für data science: <https://bookdown.org/rdpeng/rprogdatascience/>

Wickham, H.: R for data science: <https://r4ds.had.co.nz/>

## Weitere Info-Quellen

##### Tutorials zu R/RStudio (themenspezifisch)

z.B. Datanovia: <https://www.datanovia.com/en/>

##### Forum für Fragen zu R und anderen Programmiersprachen

z.B. Stack Overflow: <https://stackoverflow.com>

::: {.callout-tip appearance="simple"}
## "Such"-Workflow
-   Frage zu R auf englisch googeln, z.B. "r cran create random csv"
-   In der Trefferliste nach Einträgen von "stackoverflow.com" suchen
-   Öffnen und "clever" lesen!!

Es erfordert etwas "Routine" die guten von den schlechten Antworten zu unterscheiden!
:::

# LTC12

## Readings

Hier dann einige Bücher welche man sich methodisch zu Herzen nehmen sollte bevor man sich in Modul 12 stürzt. Wie immer Kollege @robertson2013 oder der Herr @cutcliffe2012

::: callout-important
## Leistungsnachweis

Die Note im Modul LTC12 ergibt sich aus drei Teilkomponenten.\
- Projektpräsentation (00%)\
- xyz (00%)
:::

## Abgabe der Leistungen

Bitte alle Dokumente zur benotung inklusiv Rohdaten (\*.zip) in einer Email an die beiden Dozierenden [Dr. Rein](mailto:r.rein@dshs-koeln.de) und [Dr. Braunstein](mailto:braunstein@dshs-koeln.de) schicken.

# Tools

-   Prima Convertierung von Audio/ Video in verschiedene Formate\
-   fuer Fortgeschrittene auch mit FFMPG

## Programmming

-   Link zum VS code bzw. VS codium
-   Link zu Rstudio bzw. dem neuen Namen

## Motion capture/analysis

-   Link zu Mokka
-   Link zu [Kinovea](https://www.kinovea.org) einem Tool mit dem Ihr ganz ohne Mühe die meisten Videoformate einsesen könnt und schon ziemlich viel an Auswertetools an die Hand bekommt.
-   Link zum Vicon PlugIn Gait
-   Link zu

# Contacts

## Dr. Braunstein

Contact me preferably via email. If this do not work for you try to get me on the phone in my office or show up in the lab or office during 'normal academic hours'.

Dr. Bjoern Braunstein\
Am Sportpark Müngersdorf 6\
50933 Cologne\
Germany\
<br /> [braunstein\@dshs-koeln.de](mailto:braunstein@dshs-koeln.de)\
+49(221)4982.5621\
Building: NaWiMedi\
Room: xxxx

```{r,echo=FALSE,}
library(leaflet)
leaflet() %>%
  setView(lng=6.8703, lat=50.93555,zoom=15)%>%
  addTiles() %>%  # Add default OpenStreetMap map tiles
  addMarkers(lng=6.8703, lat=50.93555, popup="German Sport University")%>%
  addProviderTiles(providers$CartoDB.Positron)
```

## Dr. Rein

## Dr. Seifriz

# References

::: {#refs}
:::
